version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181 
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - 8090:8080
    depends_on:
      - zookeeper
      - kafka
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - /Users/vanilla/Projects/practise/java-reactive/kafka-reactive/dockerdata/mongo:/data/db
  banking-service:
    build: ./banking-service
    container_name: banking-service
    ports:
      - 2001:2001
    depends_on:
      - zookeeper
      - kafka
      - mongodb
      - user-notification-service
      - reporting-service
      - account-management-service
  user-notification-service:
    build: ./user-notification-service
    container_name: user-notification
    ports:
      - 2002:2002
    depends_on:
      - zookeeper
      - kafka
      - mongodb
  reporting-service:
    build: ./reporting-service
    container_name: reporting-service
    ports:
      - 2003:2003
    depends_on:
      - zookeeper
      - kafka
      - mongodb
  account-management-service:
    build: ./account-management-service
    container_name: account-mgt-service
    ports:
      - 2004:2004
    depends_on:
      - zookeeper
      - kafka
      - mongodb