server:
  port: 2203
spring:
  devtools:
    restart:
      enabled: true
      log-condition-evaluation-delta: false
  data:
    mongodb:
      authentication-database: admin
      #uri: mongodb://localhost:27777/reactive
      host: localhost
      port: 27777
      database: reactive
      password: root
      username: root
  cloud:
    function:
      definition: consumeTransaction
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          autoCreateTopics: false
        bindings:
          consumeTransaction-in-0:
            consumer:
              max-attempts: 3
              back-off-initial-interval: 100
            destination: transactions
            group: reporting
            concurrency: 1
          transaction-out-0:
            destination: transactions