server:
  port: 2001
spring:
  data:
    mongodb:
      authentication-database: admin
      uri: mongodb://localhost:27017/datlabank
      database: datlabank
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:29092
          autoCreateTopics: true